Repository felangel/fresh, pull requests merged in 2020-06, with the labels that each got.

#20 Rework signout in dio example
  packages/fresh_dio/example/lib/authentication/bloc/authentication_bloc.dart
Labels: documentation

#21 feat(fresh_graphql): add authentication status stream
  .github/workflows/fresh.yaml
  .github/workflows/fresh_dio.yaml
  .github/workflows/fresh_graphql.yaml
  packages/fresh_graphql/CHANGELOG.md
  packages/fresh_graphql/example/main.dart
  packages/fresh_graphql/lib/src/fresh_link.dart
  packages/fresh_graphql/pubspec.yaml
  packages/fresh_graphql/test/fresh_test.dart
Labels: enhancement

#22 Add generic <T> parameter to 'TokenHeaderBuilder'.
  packages/fresh_dio/lib/src/fresh.dart
Labels: bug

#24 fix(fresh_dio): onResponse response is null case
  packages/fresh_dio/lib/src/fresh.dart
  packages/fresh_dio/test/fresh_test.dart
Labels: bug
